services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-mydatabase}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./volumes/db_data:/var/lib/postgresql/data
    networks:
      - hello-pulse-survey

  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    image: palm-oil-dev
    container_name: hello-pulse-survey
    volumes:
      - ./:/app
    working_dir: /app
    command: tail -f /dev/null 
    stdin_open: true    
    tty: true           
    networks:
      - hello-pulse-survey
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-mydatabase}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}


networks:
  hello-pulse-survey:
    driver: bridge
